Repository rblx-godot/rblx-godot, pull requests merged in 2025-01, with the labels that each got.

#7 New stuff
  .gitignore
  .vscode/launch.json
  Cargo.lock
  Cargo.toml
  commands.lldb
  godot/icon.png
  godot/icon.png.import
  godot/icon.svg
  godot/project.godot
  src/core/alloc/global.rs
  src/core/inheritance.rs
  src/core/instance_repl_table.rs
  src/core/instance_tag_collection.rs
  src/core/lua_macros.rs
  src/core/mod.rs
  src/core/pointers.rs
  src/core/rc/inheriting_rc.rs
  src/core/rc/mod.rs
  src/core/rc/threaded_rc.rs
  src/core/rw_lock.rs
  src/core/scheduler.rs
  src/core/state.rs
  src/core/trc/inheriting_rc.rs
  src/core/trc/threaded_rc.rs
  src/core/vm.rs
  src/core/watchdog.rs
  src/instance/actor.rs
  src/instance/instance.rs
  src/instance/mod.rs
  src/instance/model.rs
  src/instance/object.rs
  src/instance/pvinstance.rs
  src/lib.rs
  src/test.lua
  src/userdata/cframe.rs
  src/userdata/events.rs
  src/userdata/instance.rs
  src/userdata/mod.rs
  src/userdata/vectors.rs
Labels: enhancement

#15 Implementation of FastFlags, CFrame
  .gitignore
  Cargo.toml
  src/core/fastflags.rs
  src/core/lua_macros.rs
  src/core/mod.rs
  src/core/rc/inheriting_rc.rs
  src/core/rw_lock.rs
  src/core/scheduler.rs
  src/core/state.rs
  src/core/vm.rs
  src/instance/instance.rs
  src/instance/model.rs
  src/instance/object.rs
  src/lib.rs
  src/test.lua
  src/userdata/cframe.rs
  src/userdata/events.rs
  src/userdata/mod.rs
  src/userdata/vectors.rs
Labels: enhancement

#41 Add poison flag checking to `RWLock`.
  src/core/rw_lock.rs
Labels: bug

#43 Add poison flagging.
  src/core/rw_lock.rs
Labels: enhancement, bug
